name: Scheduled Event Trigger Workflow

on:
  schedule:
    - cron: '0 * * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Run scheduled task
        run: echo "This job runs every minute as per the cron schedule."
      - name: Notify completion
        run: echo "Scheduled job completed successfully."