name: Scheduled Event Trigger Workflow
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run scheduled task
        run: echo "This job runs every minute as per the cron schedule."
      - name: Notify completion
        run: echo "Scheduled job completed successfully."